# Base configs
baseurl: "https://rvarasg.github.io/tirada_del_dia"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Tirada de la semana"
subtitle: "Pio Baroja"
author: "rober"
header:
 title: "TIRADA DE LA SEMANA de Pio Baroja 1D"
 subtitle: "by rober"
footer:
 name: "Holi! ¿Qué pasa?"
 bio: "Soy rober, esto es para ustedes, gracias por confiar en mi :) Si encontráis esto, os hago una tortilla"
 github: "Hehe"
web_design: "dk"

social_urls:
  twitter: "https://www.twitter.com/rampatra_"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
